general:
  # pointsPerLevel - number of points needed to advance 1 island level.
  pointsPerLevel: 1000
  # default - the default value for blocks not listed in blockValues here.
  default: 10
  # useDiminishingReturns - If true, diminishing returns will be used for all blocks using the default scale 
  # (custom scales can be defined in the section below).
  # If useDiminishingReturns is false, the blocks listed in the dimishingReturns section will still be affected.
  useDiminishingReturns: false
  # defaultScale - the default value to use for diminishing returns. This is the number of blocks before DR starts to 
  # lower value.
  defaultScale: 10000
  # blockValues [ID: VALUE] - the blocks listed below will have custom values instead of the default.
  # Syntax: ID : VALUE
  #  ID := BlockID | BlockID:SubType | BlockID:SubTypeMin-SubTypeMax
  # I.e.
  # '1:0': 10 # Will give 10 points per STONE
  # '1:1': 20 # Will give 20 points per GRANITE
  # '1:2-6': 25 # Will give 25 points for Polished Granite(2), Andesite(3), Polished Andesite(4), Diorite(5) and 
  # Polished Diorite(6).
blockValues:
  '1:0': 10
  '1:1': 12.5
  '1:2': 15
  '1:3': 12.5
  '1:4': 15
  '1:5': 12.5
  '1:6': 15
  '2': 20
  '3': 20
  '3:1': 25
  '3:2': 25
  '4': 10
  '5': 10
  '6': 0
  '7': 0
  '8': 0
  '9': 0
  '10': 0
  '11': 0
  '12:0': 20
  '12:1': 22.5
  '13': 20
  '14': 500
  '15': 200
  '16': 200
  '17:0': 10
  '17:1-5': -1
  '18:0-3': 0
  '19': 50
  '19:1': 50
  '20': 50
  '21': 300
  '22': 500
  '24:0': 80
  '24:1-2': -1
  '25': 20
  '26': 1000
  '27': 20
  '28': 20
  '29': 60
  '30': 20
  '33': 40
  '34': 0
  '35:0': 50
  '35:1-15': -1
  '36': 0
  '41': 1500
  '42': 300
  '43:0': 10
  '43:1': 20
  '43:2-3': 10
  '43:4': 50
  '43:5-6': 20
  '43:7': 100
  '44:0': 5
  '44:1': 40
  '44:2': 5
  '44:3': 5
  '44:4': 25
  '44:5': 20
  '44:6': 20
  '44:7': 50
  '45': 50
  '46': 80
  '47': 50
  '48': 30
  '49': 200
  '51': 0
  '53': 15
  '55': 0
  '56': 400
  '57': 5000
  '59': 0
  '60': 40
  '63': 0
  '64': 20
  '65': 0
  '67': 15
  '68': 0
  '70': 0
  '71': 200
  '72': 0
  '78': 0
  '79': 50
  '80': 50
  '81': 0
  '82': 50
  '83': 0
  '84': 50
  '85': 17.5
  '89': 20
  '90': 0
  '91': 20
  '92': 50
  '95:0': 25
  '95:1-15': -1
  '96': 30
  '98:0': 40
  '98:1-3': -1
  '99': 100
  '100': 100
  '101': 12.5
  '103': 0
  '104': 0
  '105': 0
  '107': 40
  '108': 75
  '109': 30
  '110': 20
  '112': 20
  '113': 60
  '114': 30
  '116': 150
  '117': 30
  '118': 155
  '119': 0
  '120': 0
  '121': 15
  '122': 5000
  '123': 20
  '124': 20
  '125:0': 10
  '125:1-5': -1
  '126:0': 5
  '126:1-5': -1
  '127': 0
  '128': 120
  '129': 200
  '130': 2000
  '133': 1000
  '134': 15
  '135': 15
  '136': 15
  '137': 0
  '138': 2000
  '141': 0
  '142': 0
  '144:0': 1000
  '144:1-4': -1
  '145:0': 150
  '145:1-2': -1
  '146': 20
  '147': 115
  '148': 50
  '151': 200
  '152': 150
  '153': 50
  '154': 125
  '155:0': 100
  '155:1-2': -1
  '156': 150
  '157': 20
  '159:0': 50
  '159:1-15': -1
  '161:0-1': 0
  '163': 15
  '164': 15
  '165': 250
  '166': 0
  '167': 20
  '168': 50
  '168:1': 50
  '168:2': 50
  '169': 50
  '170': 20
  '171:0': 20
  '171:1-15': -1
  '172': 20
  '173': 500
  '174': 15
  '176': 20
  '177': 20
  '178': 200
  '179:0': 25
  '179:1-2': -1
  '180': 20
  '181': 20
  '182': 12.5
  '183': 40
  '184': 40
  '185': 40
  '186': 40
  '187': 40
  '188': 17.5
  '189': 17.5
  '190': 17.5
  '191': 17.5
  '192': 17.5
  '193': 20
  '194': 20
  '195': 20
  '196': 20
  '197': 20

# blockLimits - blocks listed here will stop adding to island levels after the given number of blocks.
blockLimits:
  '4': 10000
  '19': 20
  '26': 1
  '87': 10000
  '88': 10000
  '106': 25
  '117': 10
  '118': 10
  '121': 10000
  '122': 2
  '154': 10
  '130': 3
  '145:0-2': 5
  '138': 10
# diminishingReturns [ID: SCALE] - The listed blocks will add more to island level before SCALE number of blocks are counted towards the island level, 
# and less to island level after SCALE.
diminishingReturns:
  '1:0-6': 10000
  '2': 10000
  '3:0-2': 10000
  '5': 10000
  '12:0-1': 10000
  '17:0-5': 100
  '31': 100
  '35:0-15': 64
  '37': 100
  '38': 100
  '39': 100
  '40': 100
  '43:0-7': 10000
  '44:0-7': 10000
  '49': 50
  '67': 5000
  '85': 5000
  '98:0-3': 20000
  '99': 30
  '100': 30
  '107': 100
  '108': 5000
  '109': 5000
  '110': 10000
  '112': 20000
  '113': 5000
  '114': 5000
  '125:0-5': 10000
  '126:0-5': 10000
  '128': 5000
  '139': 5000
  '155:0-2': 5000
  '156': 5000
  '162': 100
  '162:1': 100
  '165': 100
  '167': 10
  '171:0-15': 5000
  '173': 100
  '176': 20
  '177': 20
  '181': 20000
  '182': 20000
  '183': 100
  '184': 100
  '185': 100
  '186': 100
  '187': 100
  '188': 5000
  '189': 5000
  '190': 5000
  '191': 5000
  '192': 5000
version: 5
